package dpi.atlas.service.cm.core;

/**
 * TJCommand class
 *
 * @author <a href="mailto:alireza@taherkordi.com">Alireza Taherkordi</a>
 * @version $Revision: 1.7 $ $Date: 2007/10/29 14:04:29 $
 */
public class TJCommand {

    public static final String CMD_FAST_CASH = "FCSH";  // 520
    public static final String CMD_FAST_CASH_REVERSAL = "FCSHR";  // 020
    public static final String CMD_TRANSFER_FUND = "FT";  // 540
    public static final String CMD_TRANSFER_FUND_POS = "FTPS";  // 540
    public static final String CMD_TRANSFER_FUND_GROUP_CARD = "FTGRP";  // 540
    public static final String CMD_TRANSFER_FUND_GROUP_CARD_REVERSAL = "FTGRPR";  // 040
    public static final String CMD_TRANSFER_FUND_REVERSAL = "FTR";  // 040

    public static final String  CB_FUND_TRANSFER_CMD = "CBFT";


    public static final String CMD_FIVE_TRANSATION_LIST = "5STM";  // 555
    public static final String CMD_BILL_PAYMENT = "BLPY";  // 565
    public static final String CMD_BILL_PAYMENT_REVERSAL = "BLPYR";  // 065
    public static final String CMD_PAYMENT_GATEWAY_BLPY_LOCAL = "BLPYPGL";  // 565 BLPY PaymentGateway - LOCAL
    public static final String CMD_POS_BLPY_LOCAL = "BLPYPSL";
    public static final String CMD_MOBILE_PAYMENT_BLPY_LOCAL = "BLPYMPL";  // 565
    public static final String CMD_CASH_WITHDRAWAL = "CSHW";  // 580
    public static final String CMD_CASH_WITHDRAWAL_REVERSAL = "CSHWR";  // 080
    public static final String CMD_LORO = "LORO";  // 599
    public static final String CMD_LORO_REVERSAL = "LOROR";  // 099

    public static final String CMD_NETWORK_FAST_CASH = "NFCSH";  // 620
    public static final String CMD_NETWORK_FAST_CASH_REVERSAL = "NFCSHR";  // 720

    public static final String CMD_CASH_REQUEST = "CSHR";  // 621
    public static final String CMD_SPARROW_POS_BRANCH_SHETAB_CASH_REQUEST = "SPBSCSHR";  // 621
    public static final String CMD_CASH_REQUEST_REVERSAL = "CSHRR";  // 721

    public static final String CMD_SALE_REQUEST = "SALR";  // 622
    public static final String CMD_SALE_REQUEST_REVERSAL = "SALRR";  // 722 - 710

    public static final String CMD_SALE_WITH_CASH_REQUEST = "SALCSHR";  // 624
    public static final String CMD_SALE_WITH_CASH_REQUEST_REVERSAL = "SALCSHRR";  // 724
    public static final String CMD_NETWORK_FUND_TRANSFER_TEJ2NONTEJ = "NFTT2NT";  // 636
    public static final String CMD_NETWORK_FUND_TRANSFER_TEJ2NONTEJ_REVERSAL = "NFTT2NTR";  // 736
    public static final String CMD_NETWORK_FUND_TRANSFER_NONTEJ2TEJ = "NFTNT2T";  // 637
    public static final String CMD_NETWORK_FUND_TRANSFER_NONTEJ2TEJ_REVERSAL = "NFTNT2TR";  // 737
    public static final String CMD_NETWORK_FUND_TRANSFER_NONTEJ2TEJ_POS = "NFTNT2TPS";  // 637
    public static final String CMD_NETWORK_FUND_TRANSFER_NONTEJ2TEJ_POS_BRANCH = "NFTNT2TPB";  // 637
    public static final String CMD_NETWORK_FUND_TRANSFER_NONTEJ2TEJ_PG = "NFTNT2TPG";  // 637
    public static final String CMD_NETWORK_FUND_TRANSFER_NONTEJ2TEJ_MP = "NFTNT2TMP";  // 637
    public static final String CMD_NETWORK_FUND_TRANSFER_NONTEJ2TEJ_KIOSK = "NFTNT2TKS";  // 637
    public static final String CMD_NETWORK_FUND_TRANSFER_TEJ2TEJ = "NFTT2T";  // 640
    public static final String CMD_NETWORK_FUND_TRANSFER_TEJ2TEJ_REVERSAL = "NFTT2TR";  // 740
    public static final String CMD_NETWORK_FUND_TRANSFER_TEJ2TEJ_POS = "NFTT2TPS";  // 640
    public static final String CMD_NETWORK_FUND_TRANSFER_TEJ2TEJ_POS_BRANCH = "NFTT2TPB";  // 640
    public static final String CMD_FUND_TRANSFER_TEJ2TEJ_POS_BRANCH = "FTT2TPB";  // 640
    public static final String CMD_NETWORK_FUND_TRANSFER_TEJ2TEJ_PG = "NFTT2TPG";  // 640
    public static final String CMD_NETWORK_FUND_TRANSFER_TEJ2TEJ_REVERSAL_PG = "NFTT2TRPG";  // 740
    public static final String CMD_FUND_TRANSFER_TEJ2TEJ_MP = "FTT2TMP";  // 640
    public static final String CMD_NETWORK_FUND_TRANSFER_TEJ2TEJ_KIOSK = "NFTT2TKS";  // 640
    public static final String CMD_NETWORK_FUND_TRANSFER_GROUP_CARD_PG = "NFTGRPPG";  // 640
    public static final String CMD_NETWORK_FUND_TRANSFER_GROUP_CARD_REVERSAL_PG = "NFTGRPRPG";  // 740
    public static final String CMD_NETWORK_BILL_PAYMENT = "NBLPY";  // 665
    public static final String CMD_NETWORK_BILL_PAYMENT_REVERSE = "NBLPYR";  // 765
    public static final String CMD_NETWORK_CASH_WITHDRAWAL = "NCSHW";  // 680
    public static final String CMD_NETWORK_CASH_WITHDRAWAL_REVERSAL = "NCSHWR";  // 780


    public static final String CMD_TERMINAL_RECONCILIATION = "TEREC";  // Termianl Reconciliation, THIS IS NOT 591, this transaction is generated by CFS for branch terminals

    // SGB Specific Transactions
    public static final String CMD_CASH = "CSH";  // This is a general cash transaction type for all SGB debit transactions
    public static final String CMD_DEPOSIT = "DEP";  // This is a general deposit transaction type for all SGB credit transactions
    public static final String CMD_UNBLOCK = "UNB";  // This is a general deposit transaction type for all SGB credit transactions

    public static final String CMD_DATE_RECORD = "DTRC";
    public static final String SERVICE_CFS = "cfs";
    public static final String OUTGOING = "1";
    public static final String CMD_HEADER_RECORD = "HDRC";
    public static final String CMD_DETAIL_RECORD = "DERC";
    public static final String CMD_TOTAL_RECORD = "TTRC";

    public static final String CMD_BRANCH_DEPOSIT_BATCH_GIFTCARD = "GIFBDEPBR";
    public static final String CMD_BRANCH_DEPOSIT = "DEPBRNCH";
    public static final String CMD_BRANCH_DEPOSIT_GIFTCARD = "GIFDEPBR";
    public static final String CMD_BRANCH_DEPOSIT_REVERSAL = "DEPBRNCHR";
    public static final String CMD_BRANCH_DEPOSIT_GIFTCARD_REVERSAL = "GIFDEPBRR";
    public static final String CMD_BRANCH_WITHDRAW = "CSHWBRNCH";
    public static final String CMD_BRANCH_WITHDRAW_ACH_WAGE = "ACHWGBR";
    public static final String CMD_BRANCH_WITHDRAW_RTGS_WAGE = "RTGSWGBR";
    public static final String CMD_BRANCH_WITHDRAW_ACH_WAGE_REVERSAL = "ACHWGRBR";
    public static final String CMD_BRANCH_WITHDRAW_RTGS_WAGE_REVERSAL = "RTGSWGRBR";
    public static final String CMD_BRANCH_WITHDRAW_WAGE_REVERSAL = "WGRBR";
    public static final String CMD_BRANCH_WITHDRAW_GIFTCARD = "GIFCSHWBR";
    public static final String CMD_BRANCH_WITHDRAW_REVERSAL = "CSHWBRNCHR";
    public static final String CMD_BRANCH_BALANCE = "BALBRNCH";
    public static final String CMD_BRANCH_GIFT_DEPOSIT = "GFTDEPBR";
    public static final String CMD_BRANCH_GIFT_REVOKE = "GFTREVBR";
    public static final String CMD_BRANCH_FOLLOWUP = "FLWBRNCH";
    public static final String CMD_BRANCH_CHANGE_ACCOUNT_STATUS = "BRCHNGST";
    public static final String CMD_BRANCH_RESET_ACCOUNT = "RSACCBRNCH";
    public static final String CMD_BRANCH_STATEMENT = "STMBRNCH";
    public static final String CMD_BRANCH_COUNT_STATEMENT = "STBRNCOUNT";
    public static final String CMD_BRANCH_CANCELLATION_GIFTCARD = "GIFCANBR";
    public static final String CMD_BRANCH_DISCHARGE_GIFTCARD = "GIFDCHBR";
    public static final String CMD_SIMIN_CHANGE_ACCOUNT_STATUS = "SMCHNGST";
    public static final String CMD_SIMIN_DELETE_DOCUMENT = "SMDELDOC";
    public static final String CMD_SIMIN_BALANCE = "SMBAL";


    public static final String CMD_CARD_ACCOUNT_BLOCKING = "BLCK";
    public static final String CMD_CARD_ACCOUNT_UNBLOCKING = "UNBLCK";
    public static final String CMD_SHOW_CARD_ACCOUNT_STATUS = "SHWACCST";
    public static final String RTGS_FUND_TRANSFER_CMD = "RTGSFT";
    public static final String IS_SATNA_OPEN_CMD = "RTGSST";

    public static final String RTGS_FUND_TRANSFER_REVERSAL_CMD = "RTGSFTR";
    public static final String ACH_FUND_TRANSFER_REVERSAL_CMD = "ACHFTR";
    public static final String UNBLOCK_SHARE_STOCK_AMNT_CMD = "SHRUBLK";
    public static final String SHARE_STCK_ACC_ST_CMD = "SHRST";
    public static final String SHARE_STCK_FT_CMD = "SHRSTFT";
    public static final String SHARE_STCK_FTR_CMD = "SHRSTFTR";
    public static final String SH_STCK_TRANS_LIST_CMD = "SHRSTLS";


    //paya
    public static final String ACH_FUNDTRANSFER_CMD = "ACHFT";
    public static final String GROUP_ACH_FUNDTRANSFER_CMD = "GACHFT";
    public static final String ACH_FILE_REG_CMD = "ACHFLRG";
    //Municipality bill payment followup
    public static final String MUNICIPALITY_BILL_PAYMENY_FOLLOWUP_CMD = "MNCBILLFLW";
    //Interanet
    public static final String BLOCK_ACC_BY_BLOCK_NO_CMD = "BLCKCAMNT";
    public static final String UNBLOCK_ACC_BY_BLOCK_NO_CMD = "UNBLCKAMNT";
    public static final String SHOW_BLOCK_AMNT_STATUS_CMD = "CACCBLCKST";

    /*ISO*/
    public static final String CMD_BILL_PAYMENT_VERIFICATION = "BLPYVER";
    public static final String CMD_FUND_TRANSFER_TEJ2TEJ = "FTT2T";

    //CMS
    public static final String CMD_CMS_BALANCE = "GIFBAL";
    public static final String CMD_CMS_GIFTCARD_CHARGE = "GIFCHR";
    public static final String CMD_CMS_GIFTCARD_DISCHARGE = "GIFCHRR";
    public static final String CMD_CMS_CANCELLATION = "GIFCAN";
    public static final String CMD_CMS_GIFTCARD_GET_DEPOSIT = "GIFDEP";
    public static final String CMD_CMS_BALANCE_BATCH = "GIFBTBAL";
    public static final String CMD_CMS_CHARGE_TRANSACTION = "CHRTX";
    public static final String CMD_CMS_CROUPCARD_DCHARGE= "DCHR";
    public static final String CMD_CMS_CROUPCARD_IMMEDIATE_CHARGE= "IMMCHR";
    public static final String CMD_CMS_CROUPCARD_ALL_DCHARGE= "DCHRA";
    public static final String CMD_CMS_WFP_STATEMENT = "WFPSTM";
    public static final String CMD_CARD_BALANCE = "CARDBAL";
    public static final String CMD_CARD_STATEMENT = "CARDSTM";
    public static final String CMD_GROUP_ACCOUNT_STATEMENT = "ACCSTM";

    //Tourist
    public static final String CMD_TOURIST_BALANCE = "BLNCTRST";
    public static final String CMD_TOURIST_CARD_STATEMENT = "CDSTTRST";
    public static final String CMD_TOURIST_CHARGE_STATEMENT = "CHSTTRST";
    public static final String CMD_TOURIST_CHARGE = "CHRGTRST";
    public static final String CMD_TOURIST_DISCHARGE = "DSCHTRST";
    public static final String CMD_TOURIST_CARD_REVOKE = "CDRVTRST";
    public static final String CMD_TOURIST_FOLLOWUP = "FLWUTRST";
    public static final String CMD_TOURIST_FUND_TRANSFER = "FTTRST";

    public static final String CMD_BRANCH_GIFTCARD_PREFIX = "GIF";
    //Credits
    public static final String CMD_CREDITS_BALANCE = "BALCRDTS";
    public static final String CMD_CREDITS_STATEMENT = "STMCRDTS";
    public static final String CMD_CREDITS_DEPOSIT = "DEPCRDTS";
    public static final String CMD_CREDITS_DEPOSIT_REVERSAL = "DEPCRDTSR";
    public static final String CMD_CREDITS_WITHDRAW = "CSHWCRDTS";
    public static final String CMD_CREDITS_WITHDRAW_REVERSAL = "CSHWCRDTSR";
    public static final String CMD_CREDITS_FOLLOWUP = "FLWCRDTS";
    public static final String CMD_CREDITS_PICHACK_CHECK_STATUS = "PCHSTCRDTS";

    //AMX
    public static final String CMD_AMX_CHANGE_ACCOUNT_STATUS = "AMXCHGST";

    //remittance
    public static final String CMD_BRANCH_WITHDRAW_REMITTANCE = "CSHREMBR";

    //Safe Box
    public static final String CMD_FUND_TRANSFER_SAFE_BOX = "FTSAFEBX";
    public static final String CMD_FUND_TRANSFER_REVERSE_SAFE_BOX = "FTRSAFEBX";
    public static final String CMD_FOLLOW_UP_SAFE_BOX = "FLWSAFEBX";

    //siminStatment
    public static final String CMD_SIMIN_STATEMENT = "STMSIMTS";

    //ATM
    public static final String CMD_BRANCH_WITHDRAW_ATM="CHSWATM";
    public static final String CMD_BRANCH_DEPOSIT_ATM="DEPATM";
    public static final String CMD_BRANCH_ATM_WITHDRAW_REVERSAL="CHSWATMR";
    public static final String CMD_BRANCH_ATM_DEPOSIT_REVERSAL="DEPATMR";


    //SMS
    public static final String CMD_SMS_BALANCE = "BALSMS";
    public static final String CMD_FOLLOW_UP_SMS = "FLWUSMS";
    public static final String CMD_WAGE_SMS = "WAGESMS";
    public static final String CMD_ACTIVE_SMS = "ACTESMS";
    public static final String CMD_DISABLE_SMS = "DISSMS";

    //Deposit Stock
    public static final String CMD_DEPOSIT_STOCK_PG = "DEPSTPG";
    public static final String CMD_DEPOSIT_STOCK_REVERSE_PG = "DEPSTPGR";
    public static final String CMD_FOLLOW_UP_PG = "FLWDEPST";
    public static final String CMD_FEE_STOCK_PG = "FEESTPG";


    //Branch Paya
    public static final String CMD_PAYA_DEPOSIT = "DEPPAYA";
    public static final String CMD_RESEN_PAYA = "RESNPAYA";

    //SiminChangeStatusCBI
    public static final String CMD_SIMIN_CHANGE_CBI_STATUS = "SMCHNGCB";

    //Financial GroupBlock-UnBlock
    public static final String CMD_FINANCIAL_GROUP_BLOCK= "FINBLCK";
    public static final String CMD_FINANCIAL_GROUP_UNBLOCK= "FINUNBLCK";

    //Marhoonat Insurance
    public static final String CMD_FUND_TRANSFER_MARHOONAT_INSURANCE = "FTMARIN";
    public static final String CMD_FUND_TRANSFER_REVERSE_MARHOONAT_INSURANCE = "FTRMARIN";
    public static final String CMD_FOLLOW_UP_MARHOONAT_INSURANCE = "FLWMARIN";
    public static final String CMD_MARHOONAT_INSURANCE_BALANCE = "BALMARIN";


    //Sharing Fee
    public static final String SHARING_FT = "SHRFT";
    public static final String SHARING_FT_REVERSE = "SHRFTR";


    //Manzume
    public static final String CMD_MANZUME_DEPOSIT = "DEPMAN";
    public static final String CMD_MANZUME_DEPOSIT_REVERSAL = "DEPMANR";
    public static final String CMD_MANZUME_FOLLOWUP = "FLWMAN";

}
