//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.07 at 09:54:12 AM IRST 
//
package branch.dpi.atlas.service.cm.handler.cms.reCreate;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


@XmlRegistry
public class ObjectFactory {

    private final static QName _RECREATE_QNAME = new QName("", "RE_CREATE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RECREATEType }
     * 
     */
    public RECREATEType createRECREATEType() {
        return new RECREATEType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RECREATEType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RE_CREATE")
    public JAXBElement<RECREATEType> createRECREATE(RECREATEType value) {
        return new JAXBElement<RECREATEType>(_RECREATE_QNAME, RECREATEType.class, null, value);
    }

}
